# Generated by Django 4.2.1 on 2023-05-14 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='image',
            field=models.ImageField(upload_to='food_images/', verbose_name='Готовый результат'),
        ),
    ]
