# Generated by Django 4.2.1 on 2023-05-20 16:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('food', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shoping_card_user_recipe', to=settings.AUTH_USER_MODEL, verbose_name='Ингредиент'),
        ),
        migrations.AddField(
            model_name='recipes',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='recipes',
            name='favorited',
            field=models.ManyToManyField(blank=True, related_name='recipes_favorit', through='food.Favorit', to=settings.AUTH_USER_MODEL, verbose_name='В избраном'),
        ),
        migrations.AddField(
            model_name='recipes',
            name='ingredients',
            field=models.ManyToManyField(related_name='recipes', through='food.IngredientsRecipes', to='food.ingredients', verbose_name='Ингредиенты'),
        ),
        migrations.AddField(
            model_name='recipes',
            name='shopping_cart',
            field=models.ManyToManyField(blank=True, related_name='recipes_shopping_cart', through='food.ShoppingCart', to=settings.AUTH_USER_MODEL, verbose_name='В корзине'),
        ),
        migrations.AddField(
            model_name='recipes',
            name='tags',
            field=models.ManyToManyField(related_name='recipes', to='food.tag', verbose_name='Таг'),
        ),
        migrations.AddField(
            model_name='ingredientsrecipes',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_in_recipe', to='food.ingredients', verbose_name='Ингредиент'),
        ),
        migrations.AddField(
            model_name='ingredientsrecipes',
            name='recipes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_in_recipe', to='food.recipes', verbose_name='Рецепт'),
        ),
        migrations.AddConstraint(
            model_name='ingredients',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_ingredient'),
        ),
        migrations.AddField(
            model_name='favorit',
            name='recipes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorit_recipe', to='food.recipes', verbose_name='Рецепт'),
        ),
        migrations.AddField(
            model_name='favorit',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorit_user_recipe', to=settings.AUTH_USER_MODEL, verbose_name='Ингредиент'),
        ),
        migrations.AddConstraint(
            model_name='shoppingcart',
            constraint=models.UniqueConstraint(fields=('user', 'recipes'), name='unique_shoping_card'),
        ),
        migrations.AddConstraint(
            model_name='recipes',
            constraint=models.UniqueConstraint(fields=('author', 'name', 'pub_date'), name='unique_recipes'),
        ),
        migrations.AddConstraint(
            model_name='ingredientsrecipes',
            constraint=models.UniqueConstraint(fields=('ingredient', 'recipes'), name='Один вид ингредиента в рецепте'),
        ),
        migrations.AddConstraint(
            model_name='favorit',
            constraint=models.UniqueConstraint(fields=('user', 'recipes'), name='unique_favorit'),
        ),
    ]
