# Generated by Django 4.2.1 on 2023-05-24 15:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ('name',), 'verbose_name': 'Тег', 'verbose_name_plural': 'Теги'},
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='measurement_unit',
            field=models.CharField(db_comment='Ед.измерения ингредиента', help_text='Обозначте ед. измерения ингредиента', max_length=20, verbose_name='Ед. измерения'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(db_comment='Название ингредиента', help_text='Придумайте название ингредиента', max_length=200, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(db_comment='Цвет в HEX-формате', help_text='Используйте цвет в формате HEX', max_length=7, unique=True, validators=[django.core.validators.RegexValidator(regex='#[A-F0-9]{6}$')], verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(db_comment='Отображаемое название тега', help_text='Придумайте название тега', max_length=200, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(db_comment='Slug для цвета', help_text='Используйте slug состаящий из латинских букв, цифр и символа _', max_length=200, unique=True, validators=[django.core.validators.RegexValidator(regex='^[-a-zA-Z0-9_]+$')], verbose_name='Слаг'),
        ),
    ]
