# Generated by Django 4.2.1 on 2023-05-21 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_remove_recipes_unique_recipes_alter_recipes_tags_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(db_comment='Наименование тега', max_length=200, unique=True, verbose_name='Название'),
        ),
    ]
