# Generated by Django 4.2.1 on 2023-05-26 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_alter_tag_options_alter_ingredient_measurement_unit_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='recipe',
            name='unique_recipe',
        ),
    ]
