# Generated by Django 4.2.1 on 2023-05-21 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_alter_tag_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(db_comment='Видимое название тега', help_text='Видимое название тега', max_length=200, unique=True, verbose_name='Название'),
        ),
    ]
